version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: devtrack-postgres
    restart: always
    environment:
      POSTGRES_DB: devtrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "devtrack"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: devtrack-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devtrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: 407f3f61556942b083321cb17036d0bc6cff4bf51a2d5ad5a7c36a6cf9df8268cfb8414fa9cf0ee86d11f6213702be9d9f5ad30424564c703b418fb5ff45db11
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: devtrack-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    depends_on:
      - backend

volumes:
  postgres_data:
