spring.application.name=devtrack-backend

# Default Profile: PostgreSQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devtrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Configurations
devtrack.jwt.secret=${JWT_SECRET:407f3f61556942b083321cb17036d0bc6cff4bf51a2d5ad5a7c36a6cf9df8268cfb8414fa9cf0ee86d11f6213702be9d9f5ad30424564c703b418fb5ff45db11}
devtrack.jwt.expiration-ms=86400000

# Server Port
server.port=8080

# File Upload Settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Swagger UI & API Docs Path
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
